#Minecraft Survival Spectatormode by Evitonative

#General configuration
stay:
  enabled: true
  require-permission: true

#Should you be allowed to use the plugin in the air
in-air:
  enabled:
  message: "You have to touch the ground to use this command."

#Message printed to Console everytime the Server saves.
saving-message:
  enabled: true
  message: "Saving speced players"

other-players:
  enabled: true
  not-found: "Player not found"
  target-no-perms: "The Targeted player does not have the spec permission"
  target-not-on-ground: "The targeted player is not on the ground"

#Messages
messages:
  done: "Done."
  reload-error: "An error occurred while reloading the config."
  wrong-args: "Wrong number of arguments"
  not-in-console: "This command does not work in console."
  no-permissions: "I'm sorry, but you do not have permission to perform this command. Please contact your server administrators if you believe that this is a mistake."
  no-location: "You have entered spectator without using /c. You will be teleported to your respawn point."