#Spec commands
#Enable Features
allow-stay: true

#Message Configuration
saving-message: Saving speced players
not-in-console: This does not work in console
no-permissions: "I'm sorry, but you do not have permission to perform this command. Please contact your server administrators if you believe that this is a mistake."
no-location: "You have entered spectator without using /c. You will be teleported to your respawn point."
in-air: You have to touch the ground to use this command.